output_activation: "linear"
save_weights_every: 1
validate_every: 2
test_basin_file: "/central/scratch/mdemoura/Rivers/midway_data/topological_basins/topo_lv01.txt"
validation_end_date: "30/09/2019"
num_workers: 1
save_validation_results: true
metrics:
  - "NSE"
clip_gradient_norm: 1
test_start_date: "01/10/1989"
train_dir: "/central/home/mdemoura/neuralhydrology/graph-models/01-Applied-Source-Filters/runs/all_128_Ard_1308_041441/train_data"
train_end_date: "30/09/2009"
learning_rate:
  31: 1.0e-5
  0: 0.001
  21: 0.0001
dataset: "era5_grdc_sheds"
seq_length: 270
dynamic_inputs:
  - "sro_sum"
  - "ssro_sum"
  - "sp_mean"
  - "t2m_mean"
  - "str_mean"
  - "upstream"
img_log_dir: "/central/home/mdemoura/neuralhydrology/graph-models/01-Applied-Source-Filters/runs/all_128_Ard_1308_041441/img_log"
validation_basin_file: "basins.txt"
validation_start_date: "01/10/2009"
run_dir: "src/complete_simulation/model"
seed: 123
initial_forget_bias: 3
output_dropout: 0.4
allow_subsequent_nan_losses: 5
data_dir: "/central/scratch/mdemoura/Rivers/complete_simulation"
predict_last_n: 1
head: "regression"
model: "cudalstm"
static_attributes:
  - "pre_mm_syr"
  - "ari_ix_sav"
  - "area"
  - "ele_mt_sav"
  - "snw_pc_syr"
  - "slp_dg_sav"
  - "kar_pc_sse"
  - "cly_pc_sav"
  - "pet_mm_syr"
  - "for_pc_sse"
  - "snd_pc_sav"
  - "slt_pc_sav"
  - "gwt_cm_sav"
  - "run_mm_syr"
  - "soc_th_sav"
  - "swc_pc_syr"
  - "sgr_dk_sav"
  - "cmi_ix_syr"
  - "mean_dist"
  - "is_routing"
loss: "NSE"
number_of_basins: 1493
target_variables:
  - "streamflow"
train_start_date: "01/10/1999"
log_tensorboard: true
epochs: 35
commit_hash: ~
batch_size: 256
log_interval: 50
validate_n_random_basins: 500
hidden_size: 128
test_end_date: "30/09/1999"
train_basin_file: "basins.txt"
package_version: "1.6.0"
optimizer: "Adam"
device: "cuda:0"
experiment_name: "all_128_Ard"
