# midway data is assumed to be already present

[base]
base = "/central/scratch/mdemoura/Rivers"

[level]
hydro_lv = "05"

[source]
hydroatlas_shp_file = "source_data/BasinATLAS_v10_shp/BasinATLAS_v10_lev05.shp"

[midway]
basin_gauge_dict_file = "midway_data/mapping_dicts/gauge_to_basin_dict_lv05_grdc.json"
graph_dict_file = "midway_data/graph_dicts/graph_lv05.json"
grdc_nc_file = "midway_data/GRDC-Globe/grdc-merged.nc"
xd_dir = "midway_data/xd_lv05"

[simulation]
attributes_dir = "routing/attributes/attributes_lv05"
timeseries_dir = "routing/timeseries/timeseries_lv05"
routing_levels_dir = "routing/routing_lvs/routing_lvs_lv05"

[dates]
start_date = "1990-01-01"
end_date = "2014-12-31"
